In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_train = pd.read_csv('../Dataset/credit_card_transaction_train.csv')
df_test = pd.read_csv('../Dataset/credit_card_transaction_test.csv')

In [ ]:
df_train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,merch_zipcode
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0,28705.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0,NaN
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0,83236.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0,NaN
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0,22844.0

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19321 entries, 0 to 19320
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             19321 non-null  int64
 1   trans_date_trans_time  19321 non-null  object
 2   cc_num                 19321 non-null  int64
 3   merchant               19321 non-null  object
 4   category               19321 non-null  object
 5   amt                    19321 non-null  float64
 6   first                  19321 non-null  object
 7   last                   19321 non-null  object
 8   gender                 19321 non-null  object
 9   street                 19321 non-null  object
 10  city                   19321 non-null  object
 11  state                  19321 non-null  object
 12  zip                    19321 non-null  int64
 13  lat                    19321 non-null  float64
 14  long                   19321 non-null  float64
 15  city_pop               19321 non-null  int64
 16  job                    19321 non-null  object
 17  dob                    19321 non-null  object
 18  trans_num              19321 non-null  object
 19  unix_time              19320 non-null  float64
 20  merch_lat              19320 non-null  float64
 21  merch_long             19320 non-null  float64
 22  is_fraud               19320 non-null  float64
 23  merch_zipcode          16321 non-null  float64
dtypes: float64(8), int64(4), object(12)
memory usage: 3.5+ MB

In [ ]:
#these are the features with nan value
features_with_na=[features for features in df_train.columns if df_train[features].isnull().sum()>=1]
for feature in features_with_na:
    print(feature,np.round(df_train[feature].isnull().mean()*100,5), '%missing values')

unix_time 0.00518 %missing values
merch_lat 0.00518 %missing values
merch_long 0.00518 %missing values
is_fraud 0.00518 %missing values
merch_zipcode 15.52715 %missing values

In [ ]:

features_with_na

['unix_time', 'merch_lat', 'merch_long', 'is_fraud', 'merch_zipcode']

In [ ]:

df_train.duplicated().sum()

0

In [ ]:
df_train.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud', 'merch_zipcode'],
      dtype='object')

In [ ]:

df_train.drop('Unnamed: 0', inplace=True, axis=1)

In [ ]:

df_train.drop('merch_zipcode', inplace=True, axis=1)

In [ ]:
df_train.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud'],
      dtype='object')

##Data Engineering

In [ ]:
from datetime import datetime

In [ ]:
# Convert 'trans_date_trans_time' to datetime format
df_train['trans_date_trans_time'] = pd.to_datetime(df_train['trans_date_trans_time'])

# Convert 'dob' to datetime (date only)
df_train['dob'] = pd.to_datetime(df_train['dob']).dt.date

# Calculate age
df_train['age'] = df_train['dob'].apply(lambda x: datetime.now().year - x.year - ((datetime.now().month, datetime.now().day) < (x.month, x.day)))

# Drop the 'dob' column
df_train = df_train.drop(columns=['dob'])

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19321 entries, 0 to 19320
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trans_date_trans_time  19321 non-null  datetime64[ns]
 1   cc_num                 19321 non-null  int64
 2   merchant               19321 non-null  object
 3   category               19321 non-null  object
 4   amt                    19321 non-null  float64
 5   first                  19321 non-null  object
 6   last                   19321 non-null  object
 7   gender                 19321 non-null  object
 8   street                 19321 non-null  object
 9   city                   19321 non-null  object
 10  state                  19321 non-null  object
 11  zip                    19321 non-null  int64
 12  lat                    19321 non-null  float64
 13  long                   19321 non-null  float64
 14  city_pop               19321 non-null  int64
 15  job                    19321 non-null  object
 16  trans_num              19321 non-null  object
 17  unix_time              19320 non-null  float64
 18  merch_lat              19320 non-null  float64
 19  merch_long             19320 non-null  float64
 20  is_fraud               19320 non-null  float64
 21  age                    19321 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(4), object(10)
memory usage: 3.2+ MB

In [ ]:
from math import radians, cos, sin, sqrt, atan2

In [ ]:
# 1. Transaction Distance: Haversine formula
def haversine(lat1, lon1, lat2, lon2):
    # Convert degrees to radians
    R = 6371  # Radius of Earth in kilometers
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])

    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

In [ ]:
df_train['transaction_distance'] = df_train.apply(
    lambda row: haversine(row['lat'], row['long'], row['merch_lat'], row['merch_long']), axis=1)

In [ ]:
# 2. Transaction Frequency: Count transactions per user in the last 24 hours
df_train['trans_count_24hr'] = df_train.groupby('cc_num')['trans_date_trans_time'].transform(
    lambda x: x.rolling(1, closed='both').count())

In [ ]:
df_train.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,city_pop,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,age,transaction_distance,trans_count_24hr
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,3495,"Psychologist, counselling",0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0,36,78.597568,1.0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,149,Special educational needs teacher,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0,46,30.212176,1.0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,4154,Nature conservation officer,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0,63,108.206083,1.0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,1939,Patent attorney,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0,58,95.673231,1.0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,99,Dance movement psychotherapist,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0,38,77.556744,1.0